version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: next-auth-boilerplate
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=next-auth-boilerplate-db
    volumes:
      - db:/var/lib/postgresql/
    ports:
      - 5432:5432

volumes:
  db:
